
export const CREATE_COLLECTION = "CREATE_COLLECTION"

export const CREATE_COLLECTION_FAILURE = "CREATE_COLLECTION_FAILURE"

export const CREATE_COLLECTION_SUCCESS = "CREATE_COLLECTION_SUCCESS"


// ADDING AN ALREADY ADDED FILE TO A COLLECTION REMOVES THE FILE FROM THE COLLECTION

export const ADD_TO_COLLECTION = "ADD_TO_COLLECTION"

export const ADD_TO_COLLECTION_FAILURE = "ADD_TO_COLLECTION_FAILURE"

export const ADD_TO_COLLECTION_SUCCESS = "ADD_TO_COLLECTION_SUCCESS"


